---
:name: agc002
:date: 2016-07-31
:url: http://agc002.contest.atcoder.jp
:task:
  :A:
    :id: '1995'
  :B:
    :id: '1996'
  :C:
    :id: '1997'
  :D:
    :id: '1998'
  :E:
    :id: '1999'
  :F:
    :id: '2000'
