---
:name: tenka1-2016-quala
:date: 2016-07-30
:url: http://tenka1-2016-quala.contest.atcoder.jp
:task:
  :A:
    :id: '1990'
  :B:
    :id: '1991'
  :C:
    :id: '1992'
  :D:
    :id: '1993'
  :E:
    :id: '1994'
