---
:name: agc004
:date: 2016-09-04
:url: http://agc004.contest.atcoder.jp
:task:
  :A:
    :id: '2041'
  :B:
    :id: '2042'
  :C:
    :id: '2043'
  :D:
    :id: '2044'
  :E:
    :id: '2045'
  :F:
    :id: '2046'
