---
:name: s8pc-1
:url: http://s8pc-1.contest.atcoder.jp
:task:
  :A:
    :id: '1758'
  :B:
    :id: '1759'
  :C:
    :id: '1760'
  :D:
    :id: '1761'
  :E:
    :id: '1762'
  :F:
    :id: '1763'
  :G:
    :id: '1764'
  :H:
    :id: '1765'
