---
:name: agc001
:date: 2016-07-16
:url: http://agc001.contest.atcoder.jp
:task:
  :A:
    :id: '1979'
  :B:
    :id: '1980'
  :C:
    :id: '1981'
  :D:
    :id: '1982'
  :E:
    :id: '1983'
  :F:
    :id: '1984'
