---
:name: agc003
:date: 2016-08-21
:url: http://agc003.contest.atcoder.jp
:task:
  :A:
    :id: '2001'
  :B:
    :id: '2002'
  :C:
    :id: '2003'
  :D:
    :id: '2004'
  :E:
    :id: '2005'
  :F:
    :id: '2006'
